spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo_db
    username: dev_username
    password: dev_password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

logging:
  level:
    com.nirob.todo: DEBUG
    org.springframework.security: DEBUG