spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        jdbc:
          time_zone: UTC

logging:
  level:
    com.nirob.todo: INFO
    org.springframework.security: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

server:
  tomcat:
    max-threads: 200
  compression:
    enabled: true
  port: ${PORT:8080}

# Flyway Migration - Important for Neon
flyway:
  enabled: true
  baseline-on-migrate: true
  locations: classpath:db/migration
  out-of-order: true
  validate-on-migrate: false # Set to false to avoid validation issues on first deploy