spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/todo_db
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true

jwt:
  secret: 2f6e1a8c4d7b3e5f0a9c2d4e6f8a0b2d4e6f8a0b2c4d6e8f0a2c4e6f8a0b2d4e6f8a0c2e4f
  expiration: 86400000
  refresh-expiration: 604800000

logging:
  level:
    root: INFO
    com.nirob.todo: DEBUG
    org.springframework.security: INFO

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

